# Generated by Django 5.0.6 on 2025-11-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_estadisticas_pagevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
